### ISSUE TITLE
required react-native library for twilio-sync

### ISSUE THREAD

**Issue by samsol38** [twilio/sync-quickstart-ios#11]
-Is there any library available in react-native (android + ios support) for twilio-sync?

**Comment by berkus** [comment]
I don't think you need any android or  ios support for sync sdk. Just  npm install it and it should work with react-native.

**Comment by Gray-Wind** [comment]
@samsol38 Did you manage to run JS SDK for react native application?

**Comment by berkus** [comment]
no response, closing
